### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by fakegermano** [baconscript/github-issues#13]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:53:11)
Object.activate (/home/fakegermano/.atom/packages/github-issues/index.coffee:42:9)
```

**Comment by baconscript** [comment]
Fixed; confirmed working in 0.189.0
